services:
    api:
        build: .
        container_name: mi_api_node
        ports:
            - '3000:3000'
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network

    db:
        image: postgres:16
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: midb
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 3s
            timeout: 5s
            retries: 5
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        ports:
            - '5433:5432'
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
